name: Sync HostlistsRegistry assets to Gitee

on:
  schedule:
    - cron: '0 2 * * *'  # 北京时间 10:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 拉取上游最新代码
        run: |
          git config --global user.name "yangcosc"
          git config --global user.email "yzcaishui@gmail.com"
          
          git remote add upstream https://github.com/AdguardTeam/HostlistsRegistry.git
          git fetch upstream
          git reset --hard upstream/main

      - name: 只保留需要的文件
        run: |
          # 删除所有文件
          rm -rf ./*
          
          # 只创建需要的目录和文件
          mkdir -p assets
          git checkout upstream/main -- assets/filter_1.txt
          git checkout upstream/main -- assets/filter_24.txt

      - name: 推送到 Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          ssh-private-key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          source-repo: .
          destination-repo: git@gitee.com:coscyang/AdGuardSDNS.git
